# Generated by Django 4.2.1 on 2023-05-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='typeofMessage',
            field=models.TextField(default='text'),
        ),
    ]
